describe("lredis.cqueues module", function()
	local lc = require "lredis.cqueues"
	local cqueues = require "cqueues"
	local cs = require "cqueues.socket"
	it(":close closes the socket", function()
		local c, s = cs.pair()
		local r = lc.new(c)
		r:close()
		assert.same(nil, s:read())
		s:close()
	end)
	it(":ping works", function()
		local c, s = cs.pair()
		local r = lc.new(c)
		local cq = cqueues.new()
		cq:wrap(function()
			assert(r:ping() == "PONG")
		end)
		cq:wrap(function()
			assert(s:xwrite("+PONG\r\n", "bn"))
		end)
		assert(cq:loop())
		assert(cq:empty())
		r:close()
		s:close()
	end)
end)
