describe("lredis.cqueues module", function()
	local lc = require "lredis.cqueues"
	local cqueues = require "cqueues"
	local cs = require "cqueues.socket"
	it(":close closes the socket", function()
		local c, s = cs.pair()
		local r = lc.new(c)
		r:close()
		assert.same(nil, s:read())
		s:close()
	end)
	it(":ping works", function()
		local c, s = cs.pair()
		local r = lc.new(c)
		local cq = cqueues.new()
		cq:wrap(function()
			assert(r:ping() == "PONG")
		end)
		cq:wrap(function()
			assert(s:xwrite("+PONG\r\n", "bn"))
		end)
		assert(cq:loop())
		assert(cq:empty())
		r:close()
		s:close()
	end)
	it("pubsub works", function()
		local c, s = cs.pair()
		local r = lc.new(c)
		local cq = cqueues.new()
		cq:wrap(function()
			r:subscribe("foo")
			assert.same({"subscribe", "foo", 1}, r:get_next())
			assert.same({"publish", "foo", "message"}, r:get_next())
			r:unsubscribe("foo")
			assert.same({"unsubscribe", "foo", 0}, r:get_next())
			assert.same(nil, r:get_next())
		end)
		cq:wrap(function()
			assert(s:xwrite("*3\r\n$9\r\nsubscribe\r\n$3\r\nfoo\r\n:1\r\n", "bn"))
			assert(s:xwrite("*3\r\n$7\r\npublish\r\n$3\r\nfoo\r\n$7\r\nmessage\r\n", "bn"))
			assert(s:xwrite("*3\r\n$11\r\nunsubscribe\r\n$3\r\nfoo\r\n:0\r\n", "bn"))
		end)
		assert(cq:loop(1))
		assert(cq:empty())
		r:close()
		s:close()
	end)
end)
